version: '3'

services:
  app:
    build: .
    volumes:
      - .:/home/python/app
    ports:
      - 3000:8000
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: schedule_generator
    tty: true
